In [1]:
import pandas as pd
import numpy as np
from jupyter_core.migrate import regex

In [2]:
nums = pd.Series([3,5,3,6])

In [3]:
nums

0    3
1    5
2    3
3    6
dtype: int64

In [4]:
df = pd.read_csv(r"employees_100.csv")

In [5]:
df

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25
...,...,...,...,...,...,...,...,...,...,...
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [6]:
df.head(

)

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02
1,154,Kavya Malhotra,engineering,Mumbai,NaN,77058,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.0,69911,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.0,69993,3,8,1,2022-12-13
4,145,Isha Nair,Data Science,NaN,32.0,88216,8,8,14,2019-11-25

In [7]:
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
95,161,Nikhil Nair,MARKETING,Chennai,22.0,55740,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
98,193,Priya Nayak,HR,NaN,23.0,56821,3,9,16,2019-08-07
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [8]:
df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
25,116,Rohan Verma,Engineering,Chennai,23.0,62693,0,4,8,2018-08-17

In [9]:
df.info

<bound method DataFrame.info of     employee_id            name    department       city   age salary  \
0           184    Swati Kapoor  Data Science    Kolkata  38.0  70719
1           154  Kavya Malhotra   engineering     Mumbai   NaN  77058
2           171    Manish Desai  Data Science  Hyderabad  23.0  69911
3           146        Neha Das   Engineering       Pune  28.0  69993
4           145       Isha Nair  Data Science        NaN  32.0  88216
..          ...             ...           ...        ...   ...    ...
95          161     Nikhil Nair     MARKETING    Chennai  22.0  55740
96          172      Neha Desai            HR    Chennai  22.0  52250
97          115      Neha Reddy     Marketing    Chennai  43.0    NaN
98          193     Priya Nayak            HR        NaN  23.0  56821
99          152     Kavya Joshi     Marketing      Delhi  44.0  69499

    experience  performance_score  projects_completed joining_date
0            5                  5                   6   2021-07-02
1            1                  8                   8   2024-02-05
2            0                  6                  18   2019-04-24
3            3                  8                   1   2022-12-13
4            8                  8                  14   2019-11-25
..         ...                ...                 ...          ...
95           0                  5                  22   2020-04-22
96           0                  5                   7   2020-11-14
97          12                  4                  10   2019-06-06
98           3                  9                  16   2019-08-07
99          10                  7                   4   2022-03-25

[100 rows x 10 columns]>

In [10]:
df.describe()

,employee_id,age,experience,performance_score,projects_completed
count,100.000000,94.000000,100.000000,100.0000,100.000000
mean,148.740000,30.861702,4.830000,5.7500,9.970000
std,27.420637,6.483397,3.755279,1.7019,5.332301
min,101.000000,22.000000,0.000000,2.0000,0.000000
25%,125.750000,25.250000,2.000000,5.0000,6.000000
50%,149.500000,31.000000,4.500000,6.0000,9.500000
75%,171.250000,35.750000,8.000000,7.0000,13.250000
max,196.000000,45.000000,17.000000,10.0000,24.000000

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          92 non-null     str
 3   city                90 non-null     str
 4   age                 94 non-null     float64
 5   salary              92 non-null     str
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    str
dtypes: float64(1), int64(4), str(5)
memory usage: 7.9 KB

In [12]:
#understand ur data first then work  on it

In [13]:
df['salary']

0     70719
1     77058
2     69911
3     69993
4     88216
      ...
95    55740
96    52250
97      NaN
98    56821
99    69499
Name: salary, Length: 100, dtype: str

In [14]:
df[['salary', 'name']] # have to use [[]]

   salary            name
0   70719    Swati Kapoor
1   77058  Kavya Malhotra
2   69911    Manish Desai
3   69993        Neha Das
4   88216       Isha Nair
..    ...             ...
95  55740     Nikhil Nair
96  52250      Neha Desai
97    NaN      Neha Reddy
98  56821     Priya Nayak
99  69499     Kavya Joshi

[100 rows x 2 columns]

In [15]:
df[df['name'] == "Swati Kapoor"]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.0,70719,5,5,6,2021-07-02

In [16]:
df.iloc[0]

employee_id                    184
name                  Swati Kapoor
department            Data Science
city                       Kolkata
age                           38.0
salary                       70719
experience                       5
performance_score                5
projects_completed               6
joining_date            2021-07-02
Name: 0, dtype: object

In [17]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [23]:
df[df['age'] > 40]

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
18,113,Ritu Nair,Finance,NaN,41.0,74778,10,7,5,2018-02-13
55,179,Arjun Das,Finance,NaN,43.0,NaN,10,7,11,2024-08-25
61,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,3,8,2021-08-07
62,155,Sanjay Das,NaN,Bangalore,45.0,74505,17,6,10,2022-06-22
76,176,Shreya Menon,Finance,NaN,41.0,80597,9,2,18,2024-11-09
80,164,Sneha Gupta,NaN,Delhi,42.0,63209,11,4,7,2021-08-07
88,124,Deepak Verma,Data Science,Hyderabad,41.0,86380,9,7,8,2024-06-05
97,115,Neha Reddy,Marketing,Chennai,43.0,NaN,12,4,10,2019-06-06
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499,10,7,4,2022-03-25

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         100 non-null    int64
 1   name                100 non-null    str
 2   department          92 non-null     str
 3   city                90 non-null     str
 4   age                 94 non-null     float64
 5   salary              92 non-null     str
 6   experience          100 non-null    int64
 7   performance_score   100 non-null    int64
 8   projects_completed  100 non-null    int64
 9   joining_date        100 non-null    str
dtypes: float64(1), int64(4), str(5)
memory usage: 7.9 KB

In [27]:
df2 = df.dropna()

In [29]:
df2.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [30]:
# removed the null values but this isnt the right way

In [32]:
df.isnull().sum()

employee_id            0
name                   0
department             8
city                  10
age                    6
salary                 8
experience             0
performance_score      0
projects_completed     0
joining_date           0
dtype: int64

In [35]:
df = df.dropna(subset = ['city'])

In [36]:
df.isnull().sum()

employee_id           0
name                  0
department            7
city                  0
age                   6
salary                7
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [37]:
df.shape

(90, 10)

In [41]:
df['age'] = df['age'].fillna(df['age'].mean())

In [42]:
df.isnull().sum(
)

employee_id           0
name                  0
department            7
city                  0
age                   0
salary                7
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [43]:
# better way to fill those null values we used mean of all the ages in age col to fill the null values in age

In [56]:
df['department'].value_counts()

department
HR                                                                                                                                                                                                                                                                                                    16
Marketing                                                                                                                                                                                                                                                                                             16
Engineering                                                                                                                                                                                                                                                                                           14
Finance                                                                                                                                                                                                                                                                                               11
Data Science                                                                                                                                                                                                                                                                                           9
Sales                                                                                                                                                                                                                                                                                                  8
<bound method Series.mode of 0     Data Science\n1      engineering\n2     Data Science\n3      Engineering\n5            Sales\n          ...     \n94    Data Science\n95       MARKETING\n96              HR\n97       Marketing\n99       Marketing\nName: department, Length: 90, dtype: str>     7
engineering                                                                                                                                                                                                                                                                                            2
 HR                                                                                                                                                                                                                                                                                                    2
 Marketing                                                                                                                                                                                                                                                                                             1
 Finance                                                                                                                                                                                                                                                                                               1
FINANCE                                                                                                                                                                                                                                                                                                1
SALES                                                                                                                                                                                                                                                                                                  1
MARKETING                                                                                                                                                                                                                                                                                              1
Name: count, dtype: int64

In [98]:
df['department'] = df['department'].str.strip().str.title()
df['department'] = df['department'].replace({'Hr': 'HR'})
df['department'] = df['department'].fillna(df['department'].mode()[0])

In [99]:
df.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [100]:
# used median to fill the null value in department

In [101]:
#df['salary'] = df['salary'].astype(int) ######################################see thishsssssss

df['salary'] = pd.to_numeric(df['salary'] , errors="coerce")

In [102]:
df.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [103]:
df['salary'] = df['salary'].fillna(df['salary'].median())

In [104]:
df.isnull().sum()

employee_id           0
name                  0
department            0
city                  0
age                   0
salary                0
experience            0
performance_score     0
projects_completed    0
joining_date          0
dtype: int64

In [105]:
###### now the data is without null value but this isnt clean yet because we can have dul values in this date set

In [122]:

df.sample()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
62,155,Sanjay Das,HR,Bangalore,45.0,74505.0,17,6,10,2022-06-22

In [124]:
df.head()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
0,184,Swati Kapoor,Data Science,Kolkata,38.000000,70719.0,5,5,6,2021-07-02
1,154,Kavya Malhotra,Engineering,Mumbai,30.761905,77058.0,1,8,8,2024-02-05
2,171,Manish Desai,Data Science,Hyderabad,23.000000,69911.0,0,6,18,2019-04-24
3,146,Neha Das,Engineering,Pune,28.000000,69993.0,3,8,1,2022-12-13
5,140,Rahul Gupta,Sales,Hyderabad,23.000000,52404.0,0,9,13,2018-12-27

In [125]:
df.tail()

,employee_id,name,department,city,age,salary,experience,performance_score,projects_completed,joining_date
94,121,Ashok Shah,Data Science,Pune,31.0,75498.0,4,7,7,2024-12-05
95,161,Nikhil Nair,Marketing,Chennai,22.0,55740.0,0,5,22,2020-04-22
96,172,Neha Desai,HR,Chennai,22.0,52250.0,0,5,7,2020-11-14
97,115,Neha Reddy,Marketing,Chennai,43.0,62310.0,12,4,10,2019-06-06
99,152,Kavya Joshi,Marketing,Delhi,44.0,69499.0,10,7,4,2022-03-25